# This is a basic workflow that is manually triggered

name: Deploy FastAPI App

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Deploy REST API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.24.4 pandas==2.0.3 scikit-learn==1.3.2 \
                      pytest==8.3.4 requests==2.32.3 fastapi==0.115.4 \
                      uvicorn==0.32.1 gunicorn httpx
          pip install flake8  # Install flake8 for linting
      
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku --version

      - name: Unshallow Git Repository
        run: |
          git fetch --all --unshallow
      # - name: Deploy to Heroku
      #   env:
      #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      #     HEROKU_APP_NAME: udacity-project
      #   run: |
      #     git remote add heroku https://git.heroku.com/udacity-project.git
      #     git push heroku master

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: udacity-project
        run: |
          heroku auth:token
          heroku git:remote -a $HEROKU_APP_NAME
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
