# This is a basic workflow that is manually triggered

name: Test FastAPI App

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Tests and Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Print current directory
        run: |
          echo "Current working directory:"
          pwd
          echo "Listing files in the working directory:"
          ls -R .

      - name: Check if model.pkl exists
        run: |
          if [ -f "./starter/model/model.pkl" ]; then
            echo "✅ model.pkl exists in ./starter/model/"
          else
            echo "❌ model.pkl NOT FOUND! Check your workflow."
            ls -R ./starter/model || echo "No 'model' directory found!"
            exit 1  # Fail the pipeline if the model is missing
          fi

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.24.4 pandas==2.0.3 scikit-learn==1.3.2 \
                      pytest==8.3.4 requests==2.32.3 fastapi==0.115.4 \
                      uvicorn==0.32.1 gunicorn httpx
          pip install flake8  # Install flake8 for linting

      - name: Run flake8 (Linting)
        run: |
          flake8 . --count --show-source --statistics

      - name: Run pytest (Testing)
        run: |
          pytest starter/starter/tests/
